// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apiGestores.Context;

namespace apiGestores.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211124145425_V1.0.0")]
    partial class V100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("apiGestores.Models.Articulos", b =>
                {
                    b.Property<int>("ArtCodigo")
                        .HasColumnName("art_codigo")
                        .HasColumnType("int");

                    b.Property<string>("ArtDenom")
                        .IsRequired()
                        .HasColumnName("art_denom")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("EstaCodigo")
                        .HasColumnName("esta_codigo")
                        .HasColumnType("int");

                    b.HasKey("ArtCodigo")
                        .HasName("PK__Articulo__D09E5E03894506EE");

                    b.HasIndex("EstaCodigo");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("apiGestores.Models.ArticulosDet", b =>
                {
                    b.Property<int>("ArtCodigo")
                        .HasColumnName("art_codigo")
                        .HasColumnType("int");

                    b.Property<string>("ArtColor")
                        .HasColumnName("art_color")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int?>("ArtPrecio")
                        .HasColumnName("art_precio")
                        .HasColumnType("int");

                    b.Property<int>("FabCodigo")
                        .HasColumnName("fab_codigo")
                        .HasColumnType("int");

                    b.Property<int?>("ModCodigo")
                        .HasColumnName("mod_codigo")
                        .HasColumnType("int");

                    b.Property<int?>("ProveCodigo")
                        .HasColumnName("prove_codigo")
                        .HasColumnType("int");

                    b.Property<int>("SucCodigo")
                        .HasColumnName("suc_codigo")
                        .HasColumnType("int");

                    b.HasKey("ArtCodigo")
                        .HasName("PK__Articulo__D09E5E0378603750");

                    b.HasIndex("FabCodigo");

                    b.HasIndex("ModCodigo");

                    b.HasIndex("ProveCodigo");

                    b.HasIndex("SucCodigo");

                    b.ToTable("ArticulosDet");
                });

            modelBuilder.Entity("apiGestores.Models.Ciudades", b =>
                {
                    b.Property<int>("CiuCodigo")
                        .HasColumnName("ciu_codigo")
                        .HasColumnType("int");

                    b.Property<string>("CiuDenom")
                        .IsRequired()
                        .HasColumnName("ciu_denom")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int?>("ProvCodigo")
                        .HasColumnName("prov_codigo")
                        .HasColumnType("int");

                    b.HasKey("CiuCodigo")
                        .HasName("PK__Ciudades__740B50BC9C3E06CF");

                    b.HasIndex("ProvCodigo");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("apiGestores.Models.Compras", b =>
                {
                    b.Property<int>("ComCodigo")
                        .HasColumnName("com_codigo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ComFecha")
                        .HasColumnName("com_fecha")
                        .HasColumnType("date");

                    b.Property<string>("ComNumerofisico")
                        .HasColumnName("com_numerofisico")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("ComObserv")
                        .HasColumnName("com_observ")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<int?>("UsuCodigo")
                        .HasColumnName("usu_codigo")
                        .HasColumnType("int");

                    b.HasKey("ComCodigo")
                        .HasName("PK__Compras__CC0BE5E885818236");

                    b.HasIndex("UsuCodigo");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("apiGestores.Models.ComprasDet", b =>
                {
                    b.Property<int>("ComCodigo")
                        .HasColumnName("com_codigo")
                        .HasColumnType("int");

                    b.Property<int>("ArtCodigo")
                        .HasColumnName("art_codigo")
                        .HasColumnType("int");

                    b.Property<int?>("ComdTotal")
                        .HasColumnName("comd_total")
                        .HasColumnType("int");

                    b.Property<int?>("ImpCodigo")
                        .HasColumnName("imp_codigo")
                        .HasColumnType("int");

                    b.HasKey("ComCodigo")
                        .HasName("PK__ComprasD__CC0BE5E82FDD6272");

                    b.HasIndex("ArtCodigo");

                    b.HasIndex("ImpCodigo");

                    b.ToTable("ComprasDet");
                });

            modelBuilder.Entity("apiGestores.Models.Cuentas", b =>
                {
                    b.Property<int>("CueCodigo")
                        .HasColumnName("cue_codigo")
                        .HasColumnType("int");

                    b.Property<int>("CiuCodigo")
                        .HasColumnName("ciu_codigo")
                        .HasColumnType("int");

                    b.Property<string>("CueCp")
                        .HasColumnName("cue_cp")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("CueDenom")
                        .IsRequired()
                        .HasColumnName("cue_denom")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("CueDireccion")
                        .HasColumnName("cue_direccion")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("CueMail")
                        .HasColumnName("cue_mail")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("CueTelefono")
                        .HasColumnName("cue_telefono")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("CueWebsite")
                        .HasColumnName("cue_website")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("EstaCodigo")
                        .HasColumnName("esta_codigo")
                        .HasColumnType("int");

                    b.HasKey("CueCodigo")
                        .HasName("PK__Cuentas__B1122C7724D0A108");

                    b.HasIndex("CiuCodigo");

                    b.HasIndex("EstaCodigo");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("apiGestores.Models.Estados", b =>
                {
                    b.Property<int>("EstaCodigo")
                        .HasColumnName("esta_codigo")
                        .HasColumnType("int");

                    b.Property<string>("EstaDenom")
                        .IsRequired()
                        .HasColumnName("esta_denom")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("EstaCodigo")
                        .HasName("PK__Estados__E380477F2005C520");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("apiGestores.Models.Fabricantes", b =>
                {
                    b.Property<int>("FabCodigo")
                        .HasColumnName("fab_codigo")
                        .HasColumnType("int");

                    b.Property<int>("EstaCodigo")
                        .HasColumnName("esta_codigo")
                        .HasColumnType("int");

                    b.Property<string>("FabDenom")
                        .IsRequired()
                        .HasColumnName("fab_denom")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<DateTime?>("FabFeccar")
                        .HasColumnName("fab_feccar")
                        .HasColumnType("date");

                    b.HasKey("FabCodigo")
                        .HasName("PK__Fabrican__EB587C809C973C02");

                    b.HasIndex("EstaCodigo");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("apiGestores.Models.Impuestos", b =>
                {
                    b.Property<int>("ImpCodigo")
                        .HasColumnName("imp_codigo")
                        .HasColumnType("int");

                    b.Property<int>("EstaCodigo")
                        .HasColumnName("esta_codigo")
                        .HasColumnType("int");

                    b.Property<string>("ImpDenom")
                        .IsRequired()
                        .HasColumnName("imp_denom")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<int>("ImpValor")
                        .HasColumnName("imp_valor")
                        .HasColumnType("int");

                    b.HasKey("ImpCodigo")
                        .HasName("PK__Impuesto__D46B2A916E977D71");

                    b.HasIndex("EstaCodigo");

                    b.ToTable("Impuestos");
                });

            modelBuilder.Entity("apiGestores.Models.Modelos", b =>
                {
                    b.Property<int>("ModCodigo")
                        .HasColumnName("mod_codigo")
                        .HasColumnType("int");

                    b.Property<int>("EstaCodigo")
                        .HasColumnName("esta_codigo")
                        .HasColumnType("int");

                    b.Property<string>("ModDenom")
                        .IsRequired()
                        .HasColumnName("mod_denom")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("ModCodigo")
                        .HasName("PK__Modelos__DD5D2196CF583B7A");

                    b.HasIndex("EstaCodigo");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("apiGestores.Models.Niveles", b =>
                {
                    b.Property<int>("NivCodigo")
                        .HasColumnName("niv_codigo")
                        .HasColumnType("int");

                    b.Property<int>("EstaCodigo")
                        .HasColumnName("esta_codigo")
                        .HasColumnType("int");

                    b.Property<string>("NivDenom")
                        .HasColumnName("niv_denom")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("NivCodigo")
                        .HasName("PK__Niveles__E280267F6224172F");

                    b.HasIndex("EstaCodigo");

                    b.ToTable("Niveles");
                });

            modelBuilder.Entity("apiGestores.Models.Paises", b =>
                {
                    b.Property<int>("PaisCodigo")
                        .HasColumnName("pais_codigo")
                        .HasColumnType("int");

                    b.Property<string>("PaisDenom")
                        .IsRequired()
                        .HasColumnName("pais_denom")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("PaisCodigo")
                        .HasName("PK__Paises__872D88226C3917BE");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("apiGestores.Models.Proveedores", b =>
                {
                    b.Property<int>("ProveCodigo")
                        .HasColumnName("prove_codigo")
                        .HasColumnType("int");

                    b.Property<int>("CiuCodigo")
                        .HasColumnName("ciu_codigo")
                        .HasColumnType("int");

                    b.Property<int>("EstaCodigo")
                        .HasColumnName("esta_codigo")
                        .HasColumnType("int");

                    b.Property<string>("ProveCp")
                        .HasColumnName("prove_cp")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("ProveDenom")
                        .IsRequired()
                        .HasColumnName("prove_denom")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ProveDireccion")
                        .HasColumnName("prove_direccion")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ProveMail")
                        .HasColumnName("prove_mail")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("ProveTelefono")
                        .HasColumnName("prove_telefono")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("ProveWebsite")
                        .HasColumnName("prove_website")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("ProveCodigo")
                        .HasName("PK__Proveedo__E6C50B97B26ECF0C");

                    b.HasIndex("CiuCodigo");

                    b.HasIndex("EstaCodigo");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("apiGestores.Models.Provincias", b =>
                {
                    b.Property<int>("ProvCodigo")
                        .HasColumnName("prov_codigo")
                        .HasColumnType("int");

                    b.Property<int?>("PaisCodigo")
                        .HasColumnName("pais_codigo")
                        .HasColumnType("int");

                    b.Property<string>("ProvDenom")
                        .IsRequired()
                        .HasColumnName("prov_denom")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("ProvCodigo")
                        .HasName("PK__Provinci__65092373FD312A69");

                    b.HasIndex("PaisCodigo");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("apiGestores.Models.Reparaciones", b =>
                {
                    b.Property<int>("RepaCodigo")
                        .HasColumnName("repa_codigo")
                        .HasColumnType("int");

                    b.Property<int>("CueCodigo")
                        .HasColumnName("cue_codigo")
                        .HasColumnType("int");

                    b.Property<int>("EstaCodigo")
                        .HasColumnName("esta_codigo")
                        .HasColumnType("int");

                    b.Property<DateTime>("RepaFeccar")
                        .HasColumnName("repa_feccar")
                        .HasColumnType("date");

                    b.Property<DateTime>("RepaFeccie")
                        .HasColumnName("repa_feccie")
                        .HasColumnType("date");

                    b.Property<string>("RepaObserv")
                        .HasColumnName("repa_observ")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("RepaCodigo")
                        .HasName("PK__Reparaci__481DC7E2FB77EF17");

                    b.HasIndex("CueCodigo");

                    b.HasIndex("EstaCodigo");

                    b.ToTable("Reparaciones");
                });

            modelBuilder.Entity("apiGestores.Models.ReparacionesDet", b =>
                {
                    b.Property<int>("RepaCodigo")
                        .HasColumnName("repa_codigo")
                        .HasColumnType("int");

                    b.Property<int?>("ArtCodigo")
                        .HasColumnName("art_codigo")
                        .HasColumnType("int");

                    b.Property<string>("RepadAccion")
                        .HasColumnName("repad_accion")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<int?>("RepadPrecio")
                        .HasColumnName("repad_precio")
                        .HasColumnType("int");

                    b.HasKey("RepaCodigo")
                        .HasName("PK__Reparaci__481DC7E2880CD0F6");

                    b.HasIndex("ArtCodigo");

                    b.ToTable("ReparacionesDet");
                });

            modelBuilder.Entity("apiGestores.Models.Reportes", b =>
                {
                    b.Property<int>("RepCodigo")
                        .HasColumnName("rep_codigo")
                        .HasColumnType("int");

                    b.Property<DateTime>("RepFecha")
                        .HasColumnName("rep_fecha")
                        .HasColumnType("date");

                    b.Property<string>("RepObserv")
                        .HasColumnName("rep_observ")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<int?>("ReptipoCodigo")
                        .HasColumnName("reptipo_codigo")
                        .HasColumnType("int");

                    b.Property<int>("SucCodigo")
                        .HasColumnName("suc_codigo")
                        .HasColumnType("int");

                    b.HasKey("RepCodigo")
                        .HasName("PK__Reportes__3EBC75FE87C6A77C");

                    b.HasIndex("ReptipoCodigo");

                    b.HasIndex("SucCodigo");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("apiGestores.Models.ReportesDet", b =>
                {
                    b.Property<int>("RepCodigo")
                        .HasColumnName("rep_codigo")
                        .HasColumnType("int");

                    b.Property<int>("ArtCodigo")
                        .HasColumnName("art_codigo")
                        .HasColumnType("int");

                    b.Property<int>("CueCodigo")
                        .HasColumnName("cue_codigo")
                        .HasColumnType("int");

                    b.Property<int?>("RepCantidad")
                        .HasColumnName("rep_cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("RepTotal")
                        .HasColumnName("rep_total")
                        .HasColumnType("int");

                    b.HasKey("RepCodigo")
                        .HasName("PK__Reportes__3EBC75FE60BCA933");

                    b.ToTable("ReportesDet");
                });

            modelBuilder.Entity("apiGestores.Models.ReportesTipos", b =>
                {
                    b.Property<int>("ReptipoCodigo")
                        .HasColumnName("reptipo_codigo")
                        .HasColumnType("int");

                    b.Property<string>("ReptipoDenom")
                        .IsRequired()
                        .HasColumnName("reptipo_denom")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("ReptipoCodigo")
                        .HasName("PK__Reportes__8B9E238873C7F0CC");

                    b.ToTable("ReportesTipos");
                });

            modelBuilder.Entity("apiGestores.Models.Sucursales", b =>
                {
                    b.Property<int>("SucCodigo")
                        .HasColumnName("suc_codigo")
                        .HasColumnType("int");

                    b.Property<string>("SucDenom")
                        .IsRequired()
                        .HasColumnName("suc_denom")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("SucCodigo")
                        .HasName("PK__Sucursal__141321F478995D83");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("apiGestores.Models.Usuarios", b =>
                {
                    b.Property<int>("UsuCodigo")
                        .HasColumnName("usu_codigo")
                        .HasColumnType("int");

                    b.Property<int>("EstaCodigo")
                        .HasColumnName("esta_codigo")
                        .HasColumnType("int");

                    b.Property<int>("NivCodigo")
                        .HasColumnName("niv_codigo")
                        .HasColumnType("int");

                    b.Property<int>("SucCodigo")
                        .HasColumnName("suc_codigo")
                        .HasColumnType("int");

                    b.Property<string>("UsuPass")
                        .IsRequired()
                        .HasColumnName("usu_pass")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("UsuUser")
                        .IsRequired()
                        .HasColumnName("usu_user")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("UsuCodigo")
                        .HasName("PK__Usuarios__F232FBD133C255C3");

                    b.HasIndex("EstaCodigo");

                    b.HasIndex("NivCodigo");

                    b.HasIndex("SucCodigo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("apiGestores.Models.Articulos", b =>
                {
                    b.HasOne("apiGestores.Models.Estados", "EstaCodigoNavigation")
                        .WithMany("Articulos")
                        .HasForeignKey("EstaCodigo")
                        .HasConstraintName("FK__Articulos__esta___5070F446")
                        .IsRequired();
                });

            modelBuilder.Entity("apiGestores.Models.ArticulosDet", b =>
                {
                    b.HasOne("apiGestores.Models.Articulos", "ArtCodigoNavigation")
                        .WithOne("ArticulosDet")
                        .HasForeignKey("apiGestores.Models.ArticulosDet", "ArtCodigo")
                        .HasConstraintName("FK__Articulos__mod_c__534D60F1")
                        .IsRequired();

                    b.HasOne("apiGestores.Models.Fabricantes", "FabCodigoNavigation")
                        .WithMany("ArticulosDet")
                        .HasForeignKey("FabCodigo")
                        .HasConstraintName("FK__Articulos__fab_c__5441852A")
                        .IsRequired();

                    b.HasOne("apiGestores.Models.Modelos", "ModCodigoNavigation")
                        .WithMany("ArticulosDet")
                        .HasForeignKey("ModCodigo")
                        .HasConstraintName("FK__Articulos__mod_c__571DF1D5");

                    b.HasOne("apiGestores.Models.Proveedores", "ProveCodigoNavigation")
                        .WithMany("ArticulosDet")
                        .HasForeignKey("ProveCodigo")
                        .HasConstraintName("FK__Articulos__prove__5629CD9C");

                    b.HasOne("apiGestores.Models.Sucursales", "SucCodigoNavigation")
                        .WithMany("ArticulosDet")
                        .HasForeignKey("SucCodigo")
                        .HasConstraintName("FK__Articulos__suc_c__5535A963")
                        .IsRequired();
                });

            modelBuilder.Entity("apiGestores.Models.Ciudades", b =>
                {
                    b.HasOne("apiGestores.Models.Provincias", "ProvCodigoNavigation")
                        .WithMany("Ciudades")
                        .HasForeignKey("ProvCodigo")
                        .HasConstraintName("FK__Ciudades__prov_c__2B3F6F97");
                });

            modelBuilder.Entity("apiGestores.Models.Compras", b =>
                {
                    b.HasOne("apiGestores.Models.Usuarios", "UsuCodigoNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("UsuCodigo")
                        .HasConstraintName("FK__Compras__usu_cod__619B8048");
                });

            modelBuilder.Entity("apiGestores.Models.ComprasDet", b =>
                {
                    b.HasOne("apiGestores.Models.Articulos", "ArtCodigoNavigation")
                        .WithMany("ComprasDet")
                        .HasForeignKey("ArtCodigo")
                        .HasConstraintName("FK__ComprasDe__art_c__656C112C")
                        .IsRequired();

                    b.HasOne("apiGestores.Models.Compras", "ComCodigoNavigation")
                        .WithOne("ComprasDet")
                        .HasForeignKey("apiGestores.Models.ComprasDet", "ComCodigo")
                        .HasConstraintName("FK__ComprasDe__comd___6477ECF3")
                        .IsRequired();

                    b.HasOne("apiGestores.Models.Impuestos", "ImpCodigoNavigation")
                        .WithMany("ComprasDet")
                        .HasForeignKey("ImpCodigo")
                        .HasConstraintName("FK__ComprasDe__imp_c__66603565");
                });

            modelBuilder.Entity("apiGestores.Models.Cuentas", b =>
                {
                    b.HasOne("apiGestores.Models.Ciudades", "CiuCodigoNavigation")
                        .WithMany("Cuentas")
                        .HasForeignKey("CiuCodigo")
                        .HasConstraintName("FK__Cuentas__ciu_cod__4CA06362")
                        .IsRequired();

                    b.HasOne("apiGestores.Models.Estados", "EstaCodigoNavigation")
                        .WithMany("Cuentas")
                        .HasForeignKey("EstaCodigo")
                        .HasConstraintName("FK__Cuentas__esta_co__4D94879B")
                        .IsRequired();
                });

            modelBuilder.Entity("apiGestores.Models.Fabricantes", b =>
                {
                    b.HasOne("apiGestores.Models.Estados", "EstaCodigoNavigation")
                        .WithMany("Fabricantes")
                        .HasForeignKey("EstaCodigo")
                        .HasConstraintName("FK__Fabricant__esta___3C69FB99")
                        .IsRequired();
                });

            modelBuilder.Entity("apiGestores.Models.Impuestos", b =>
                {
                    b.HasOne("apiGestores.Models.Estados", "EstaCodigoNavigation")
                        .WithMany("Impuestos")
                        .HasForeignKey("EstaCodigo")
                        .HasConstraintName("FK__Impuestos__esta___4316F928")
                        .IsRequired();
                });

            modelBuilder.Entity("apiGestores.Models.Modelos", b =>
                {
                    b.HasOne("apiGestores.Models.Estados", "EstaCodigoNavigation")
                        .WithMany("Modelos")
                        .HasForeignKey("EstaCodigo")
                        .HasConstraintName("FK__Modelos__esta_co__31EC6D26")
                        .IsRequired();
                });

            modelBuilder.Entity("apiGestores.Models.Niveles", b =>
                {
                    b.HasOne("apiGestores.Models.Estados", "EstaCodigoNavigation")
                        .WithMany("Niveles")
                        .HasForeignKey("EstaCodigo")
                        .HasConstraintName("FK__Niveles__esta_co__34C8D9D1")
                        .IsRequired();
                });

            modelBuilder.Entity("apiGestores.Models.Proveedores", b =>
                {
                    b.HasOne("apiGestores.Models.Ciudades", "CiuCodigoNavigation")
                        .WithMany("Proveedores")
                        .HasForeignKey("CiuCodigo")
                        .HasConstraintName("FK__Proveedor__ciu_c__3F466844")
                        .IsRequired();

                    b.HasOne("apiGestores.Models.Estados", "EstaCodigoNavigation")
                        .WithMany("Proveedores")
                        .HasForeignKey("EstaCodigo")
                        .HasConstraintName("FK__Proveedor__esta___403A8C7D")
                        .IsRequired();
                });

            modelBuilder.Entity("apiGestores.Models.Provincias", b =>
                {
                    b.HasOne("apiGestores.Models.Paises", "PaisCodigoNavigation")
                        .WithMany("Provincias")
                        .HasForeignKey("PaisCodigo")
                        .HasConstraintName("FK__Provincia__pais___286302EC");
                });

            modelBuilder.Entity("apiGestores.Models.Reparaciones", b =>
                {
                    b.HasOne("apiGestores.Models.Cuentas", "CueCodigoNavigation")
                        .WithMany("Reparaciones")
                        .HasForeignKey("CueCodigo")
                        .HasConstraintName("FK__Reparacio__cue_c__5AEE82B9")
                        .IsRequired();

                    b.HasOne("apiGestores.Models.Estados", "EstaCodigoNavigation")
                        .WithMany("Reparaciones")
                        .HasForeignKey("EstaCodigo")
                        .HasConstraintName("FK__Reparacio__esta___59FA5E80")
                        .IsRequired();
                });

            modelBuilder.Entity("apiGestores.Models.ReparacionesDet", b =>
                {
                    b.HasOne("apiGestores.Models.Articulos", "ArtCodigoNavigation")
                        .WithMany("ReparacionesDet")
                        .HasForeignKey("ArtCodigo")
                        .HasConstraintName("FK__Reparacio__art_c__5EBF139D");

                    b.HasOne("apiGestores.Models.Reparaciones", "RepaCodigoNavigation")
                        .WithOne("ReparacionesDet")
                        .HasForeignKey("apiGestores.Models.ReparacionesDet", "RepaCodigo")
                        .HasConstraintName("FK__Reparacio__repad__5DCAEF64")
                        .IsRequired();
                });

            modelBuilder.Entity("apiGestores.Models.Reportes", b =>
                {
                    b.HasOne("apiGestores.Models.ReportesTipos", "ReptipoCodigoNavigation")
                        .WithMany("Reportes")
                        .HasForeignKey("ReptipoCodigo")
                        .HasConstraintName("FK__Reportes__reptip__46E78A0C");

                    b.HasOne("apiGestores.Models.Sucursales", "SucCodigoNavigation")
                        .WithMany("Reportes")
                        .HasForeignKey("SucCodigo")
                        .HasConstraintName("FK__Reportes__suc_co__45F365D3")
                        .IsRequired();
                });

            modelBuilder.Entity("apiGestores.Models.ReportesDet", b =>
                {
                    b.HasOne("apiGestores.Models.Reportes", "RepCodigoNavigation")
                        .WithOne("ReportesDet")
                        .HasForeignKey("apiGestores.Models.ReportesDet", "RepCodigo")
                        .HasConstraintName("FK__ReportesD__rep_c__49C3F6B7")
                        .IsRequired();
                });

            modelBuilder.Entity("apiGestores.Models.Usuarios", b =>
                {
                    b.HasOne("apiGestores.Models.Estados", "EstaCodigoNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("EstaCodigo")
                        .HasConstraintName("FK__Usuarios__esta_c__398D8EEE")
                        .IsRequired();

                    b.HasOne("apiGestores.Models.Niveles", "NivCodigoNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("NivCodigo")
                        .HasConstraintName("FK__Usuarios__niv_co__38996AB5")
                        .IsRequired();

                    b.HasOne("apiGestores.Models.Sucursales", "SucCodigoNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("SucCodigo")
                        .HasConstraintName("FK__Usuarios__suc_co__37A5467C")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
